steps:

# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run']

# deploy
  name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']